# The langurage for display
core.language: en-US

# The delay of each notices show (second)
auto_notices.delay: 300

# The max count of each players' homes
sethome.max_home_count: 3

# The max tpa request time (second)
tpa.request_max_wait_time: 30